version: 2

sources:
  - name: raw
    description: "Raw data sources from CSV files"
    tables:
      - name: exchange_rates
        description: "Exchange rates data for currency conversion"
        columns:
          - name: currency_from
            description: "Source currency code"
            tests:
              - not_null
          - name: date
            description: "Date of the exchange rate"
            tests:
              - not_null
          - name: rate
            description: "Exchange rate to PLN"
            tests:
              - not_null
